# Generated by Django 4.2.7 on 2024-02-09 00:00

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="cta_1",
            field=models.CharField(
                blank=True,
                help_text="you first call to action text",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_1_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Another Image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_2",
            field=models.CharField(
                blank=True,
                help_text="Text to Display over the image",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_3",
            field=models.CharField(
                blank=True,
                help_text="The Text on the call to action button",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="customer_review",
            field=wagtail.fields.StreamField(
                [
                    (
                        "review",
                        wagtail.blocks.StructBlock(
                            [
                                ("review_text", wagtail.blocks.CharBlock()),
                                ("person", wagtail.blocks.CharBlock()),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Customer Reviews",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="This is here as the Main image on your home page. The first one",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="main_image_subText",
            field=models.CharField(
                blank=True,
                help_text="this is the samll text you will have under your main Image text",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="main_image_text",
            field=models.CharField(
                blank=True,
                help_text="This is your main image text like your Title and name.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="social_media",
            field=wagtail.fields.StreamField(
                [
                    (
                        "socials",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "logo",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=True
                                    ),
                                ),
                                ("your_link", wagtail.blocks.CharBlock(required=True)),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Social Media Links",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="story_text_1",
            field=models.CharField(
                blank=True,
                help_text="your first story text or description. The story in short",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="story_title_1",
            field=models.CharField(
                blank=True,
                help_text="your first Story title",
                max_length=255,
                null=True,
            ),
        ),
    ]
