# Generated by Django 4.2.7 on 2024-02-09 12:22

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_homepage_customer_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="customer_review",
            field=wagtail.fields.StreamField(
                [
                    (
                        "review",
                        wagtail.blocks.StructBlock(
                            [
                                ("review_text", wagtail.blocks.CharBlock()),
                                ("person", wagtail.blocks.CharBlock()),
                                (
                                    "transformation_photo",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Customer Reviews",
            ),
        ),
    ]
